//go:build ignore

// Code generated by github.com/calvinsomething/errcode.
package errcode

import (
	"encoding/json"
	"errors"
	"fmt"
)

// NewErrorFunc is the function called when constructing the Error
// returned by errcode.New and any error code func calls.
// Call DefaultNewErrorFunc from within the NewErrorFunc implementation
// to construct the Error object.
var NewErrorFunc = DefaultNewErrorFunc

type (
	pError struct {
		Code    string `json:"code"`
		Message string `json:"message"`

		wrapped error
		data    interface{}
	}

	// Error is the struct returned by errcode constructor functions.
	Error struct {
		p *pError
	}
)

// DefaultNewErrorFunc is the default constructor used by New and generated errcode functions.
// Can be overriden by reassigning NewErrorFunc.
func DefaultNewErrorFunc(code string, message string, fmtArgs ...interface{}) Error {
	p := &pError{Code: code}

	if len(fmtArgs) != 0 {
		p.Message = fmt.Sprintf(message, fmtArgs...)
	} else {
		p.Message = message
	}

	return Error{p: p}
}

// Expose unwraps err recursively until finding an Error or Unwrap fails.
// In either case an Error is returned. An empty Error will return false when calling Error.IsValid().
func Expose(err error) Error {
	for {
		if e, ok := err.(Error); ok {
			return e
		}

		if err = errors.Unwrap(err); err == nil {
			break
		}
	}

	return Error{}
}

// New calls NewErrorFunc and returns the result.
//
// Calls to this function will be replaced with an equivalent function,
// with an error code as an identifier, when using the errcode code generation.
//
// messages can optionally be formatted if fmtArgs are passed.
func New(message string, fmtArgs ...interface{}) Error {
	if len(fmtArgs) != 0 {
		return NewErrorFunc("", fmt.Sprintf(message, fmtArgs...))
	}

	return NewErrorFunc("", message)
}

// Error returns Error.Message.
func (e Error) Error() string {
	return e.p.Message
}

// Wrap wraps err and returns e.
func (e Error) Wrap(err error) Error {
	e.p.wrapped = err
	return e
}

// Unwrap returns Error.wrapped.
func (e Error) Unwrap() error {
	return e.p.wrapped
}

// MarshalJSON returns the JSON representation of the Error struct.
func (e Error) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.p)
}

// GetCode returns e's error code.
func (e Error) GetCode() string {
	return e.p.Code
}

// IsValid returns true if e's private implementation has been initialized.
func (e Error) IsValid() bool {
	return e.p != nil
}

// WithData stores i in e and returns e. Use e.GetData to access i.
func (e Error) WithData(i interface{}) Error {
	e.p.data = i
	return e
}

// GetData returns data previously stored in e with e.WithData.
func (e Error) GetData() interface{} {
	return e.p.data
}
