//go:build ignore

// Code generated by github.com/calvinsomething/errcode.
package errcode

import (
	"encoding/json"
	"errors"
	"unsafe"
)

// NewErrorFunc is the function called when constructing the Error
// returned by errcode.New and any error code func calls.
var NewErrorFunc = newError

type (
	pError struct {
		Code    string `json:"code"`
		Message string `json:"message"`

		wrapped error
		data    unsafe.Pointer
	}

	Error struct {
		*pError
	}
)

// IsErrorCode returns true if err, or any error wrapped by err, is of type Error.
func IsErrorCode(err error) bool {
	for {
		if _, ok := err.(Error); ok {
			return true
		}

		if err = errors.Unwrap(err); err == nil {
			return false
		}
	}
}

func newError(err error, code string, message ...string) Error {
	p := &pError{Code: code, wrapped: err}

	if len(message) != 0 {
		p.Message = message[0]
	}

	return Error{pError: p}
}

// New calls NewErrorFunc and returns the result.
//
// Calls to this function will be replaced with an equivalent function,
// with an error code as an identifier, when using the errcode code generation.
func New(err error, message ...string) Error {
	return NewErrorFunc(err, "", message...)
}

// Error returns Error.Message.
func (e Error) Error() string {
	return e.Message
}

// Unwrap returns Error.wrapped.
func (e Error) Unwrap() error {
	return e.wrapped
}

// MarshalJSON returns the JSON representation of the Error struct.
func (e Error) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.pError)
}

// GetCode returns e's error code.
func (e Error) GetCode() string {
	return e.Code
}

// SetData accepts any pointer type and stores it in err.
func SetData[T interface{}](err Error, data *T) {
	err.data = unsafe.Pointer(data)
}

// GetData returns the unsafe.Pointer stored in err as a *T.
func GetData[T interface{}](err Error) *T {
	return (*T)(err.data)
}
